apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: koku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
        - name: trino
          image: public.ecr.aws/v0r6c2e2/trino:latest
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 10000
          envFrom:
            - configMapRef:
                name: trino-config
            - configMapRef:
                name: koku-config
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-storage
              mountPath: /etc/trino
              readOnly: true
            - name: shared-storage
              mountPath: /data/trino/data 
            - name: shared-storage
              mountPath: /data/trino/logs 
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "0.5"
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: trino-pvc  