apiVersion: v1
kind: Service
metadata:
  name: sources-client
  namespace: koku
  labels:
    app: sources-client
spec:
  selector:
    app: sources-client
  ports:
    - name: port1
      protocol: TCP
      port: 4000
      targetPort: 8000
    - name: port2
      protocol: TCP
      port: 4001
      targetPort: 9000
  type: ClusterIP
