apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-config
  namespace: koku
data:
  HIVE_LOGLEVEL: "INFO"
  S3_ENDPOINT: "http://minio:9000"
  S3_ACCESS_KEY: "kokuminioaccess"
  S3_SECRET: "kokuminiosecret"
  S3_BUCKET_NAME: "koku-bucket"
  S3_BUCKET_PATH: "data"
  POSTGRES_SQL_SERVICE_HOST: "db"
  POSTGRES_SQL_SERVICE_PORT: "5432"
  DATABASE_NAME: "hive"
  DATABASE_USER: "hive"
  DATABASE_PASSWORD: "hive"
