apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-metastore-pvc
  namespace: koku
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi