apiVersion: apps/v1
kind: Deployment
metadata:
  name: koku-worker
  namespace: koku
  labels:
    app: koku-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koku-worker
  template:
    metadata:
      labels:
        app: koku-worker
    spec:
      containers:
        - name: koku-worker
          image: public.ecr.aws/v0r6c2e2/koku_base
          workingDir: /koku/koku
          command:
            - python
            - manage.py
            - restart_celery
          envFrom:
            - configMapRef:
                name: koku-worker-config
            - configMapRef:
                name: koku-config
          ports:
            - containerPort: 9000
            - containerPort: 5678
          imagePullPolicy: Always
