apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: koku
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: public.ecr.aws/v0r6c2e2/koku-grafana:latest 
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: koku-config  
          imagePullPolicy: Always
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: koku-grafana-pvc 
