apiVersion: apps/v1
kind: Deployment
metadata:
  name: koku-beat
  namespace: koku
  labels:
    app: koku-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koku-beat
  template:
    metadata:
      labels:
        app: koku-beat
    spec:
      containers:
        - name: koku-beat
          image: public.ecr.aws/v0r6c2e2/koku_base:latest
          workingDir: /koku/koku
          command:
            - "celery"
            - "-A"
            - "koku"
            - "beat"
            - "-l"
            - "info"
          envFrom:
            - configMapRef:
                name: koku-beat-config
            - configMapRef:
                name: koku-config
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

