apiVersion: v1
kind: Service
metadata:
  name: koku-server
  namespace: koku
spec:
  selector:
    app: koku-server
  ports:
    - protocol: TCP
      port: 8000       
      targetPort: 8000 
    - protocol: TCP
      port: 8001       
      targetPort: 9000 
  type: ClusterIP
