apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koku-pvc
  namespace: koku
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 20Gi