apiVersion: apps/v1
kind: Deployment
metadata:
  name: koku-server
  namespace: koku
  labels:
    app: koku-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koku-server
  template:
    metadata:
      labels:
        app: koku-server
    spec:
      containers:
        - name: koku-server
          image: public.ecr.aws/v0r6c2e2/koku_base:v1
          workingDir: /koku
          command: ["/koku/run_server.sh"]
          envFrom:
            - configMapRef:
                name: koku-server-config
            - configMapRef:
                name: koku-config
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 9000