apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koku-pvc
  namespace: koku
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 20Gi  
  storageClassName: gp3
