apiVersion: v1
kind: Service
metadata:
  name: koku-listener
  namespace: koku
  labels:
    app: koku-listener
spec:
  selector:
    app: koku-listener
  ports:
    - name: port1
      protocol: TCP
      port: 7001
      targetPort: 9000
    - name: port2
      protocol: TCP
      port: 7002
      targetPort: 9000
    - name: port3
      protocol: TCP
      port: 7003
      targetPort: 9000
    - name: port4
      protocol: TCP
      port: 7004
      targetPort: 9000
    - name: port5
      protocol: TCP
      port: 7005
      targetPort: 9000
    - name: port6
      protocol: TCP
      port: 7006
      targetPort: 9000
    - name: port7
      protocol: TCP
      port: 7007
      targetPort: 9000
    - name: port8
      protocol: TCP
      port: 7008
      targetPort: 9000
    - name: port9
      protocol: TCP
      port: 7009
      targetPort: 9000
    - name: port10
      protocol: TCP
      port: 7010
      targetPort: 9000
    - name: port11
      protocol: TCP
      port: 7011
      targetPort: 9000
    - name: port12
      protocol: TCP
      port: 7012
      targetPort: 9000
    - name: port13
      protocol: TCP
      port: 7013
      targetPort: 9000
    - name: port14
      protocol: TCP
      port: 7014
      targetPort: 9000
    - name: port15
      protocol: TCP
      port: 7015
      targetPort: 9000
    - name: port16
      protocol: TCP
      port: 7016
      targetPort: 9000
    - name: port17
      protocol: TCP
      port: 7017
      targetPort: 9000
    - name: port18
      protocol: TCP
      port: 7018
      targetPort: 9000
    - name: port19
      protocol: TCP
      port: 7019
      targetPort: 9000
    - name: port20
      protocol: TCP
      port: 7020
      targetPort: 9000
  type: ClusterIP
