apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koku-db-pvc
  namespace: koku
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi