apiVersion: apps/v1
kind: Deployment
metadata:
  name: koku-listener
  namespace: koku
  labels:
    app: koku-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koku-listener
  template:
    metadata:
      labels:
        app: koku-listener
    spec:
      containers:
        - name: koku-listener
          image: public.ecr.aws/v0r6c2e2/koku_base:latest
          workingDir: /koku
          command:
            - 'watchmedo'
            - 'auto-restart'
            - '--directory=./koku'
            - '--pattern=*.py'
            - '--ignore-patterns=*test*'
            - '--recursive'
            - '--'
            - 'python'
            - 'koku/manage.py'
            - 'listener'
          envFrom:
            - configMapRef:
                name: koku-listener-config
            - configMapRef:
                name: koku-config
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
            - containerPort: 5678