apiVersion: apps/v1
kind: Deployment
metadata:
  name: masu-server
  namespace: koku
  labels:
    app: masu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masu-server
  template:
    metadata:
      labels:
        app: masu-server
    spec:
      containers:
        - name: masu-server
          image: public.ecr.aws/v0r6c2e2/koku_base
          workingDir: /koku
          command: ["/koku/run_server.sh"]
          envFrom:
            - configMapRef:
                name: masu-server-config
            - configMapRef:
                name: koku-config
          ports:
            - containerPort: 8000
            - containerPort: 9000
          volumeMounts:
            - name: shared-storage
              mountPath: /koku/koku
            - name: shared-storage
              mountPath: /koku/.unleash
            - name: shared-storage
              mountPath: /koku/db_functions
            - name: shared-storage
              mountPath: /koku/scripts
            - name: shared-storage
              mountPath: /koku/run_server.sh
            - name: shared-storage
              mountPath: /etc/credentials
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: koku-pvc
