apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: koku
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
    - port: 9090
      targetPort: 9090
  selector:
    app: minio
