apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: koku
data:
  PGADMIN_DEFAULT_EMAIL: "postgres@local.dev"
  PGADMIN_DEFAULT_PASSWORD: "postgres"
  PGADMIN_PORT: "8432"
  GRAFANA_PORT: "3001"
