apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: koku
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          envFrom:
            - configMapRef:
                name: koku-config
          ports:
            - containerPort: 80
          volumeMounts:
            - name: koku-shared-storage
              mountPath: /pgadmin4/servers.json
              subPath: servers.json  
      volumes:
        - name: koku-shared-storage
          persistentVolumeClaim:
            claimName: koku-pvc 
