apiVersion: v1
kind: Service
metadata:
  name: sources-client
  namespace: koku
  labels:
    app: sources-client
spec:
  selector:
    app: sources-client
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
    - protocol: TCP
      port: 4001
      targetPort: 9000
  type: ClusterIP
