apiVersion: v1
kind: Service
metadata:
  name: subs-worker
  namespace: koku
  labels:
    app: subs-worker
spec:
  selector:
    app: subs-worker
  ports:
    - protocol: TCP
      port: 7021
      targetPort: 9000
  type: ClusterIP
