apiVersion: v1
kind: Service
metadata:
  name: trino
spec:
  selector:
    app: trino
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 10000
      targetPort: 10000
  clusterIP: None  # Exposes the service internally without a load balancer
