apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: koku
data:
  MY_NODE_ID: "localhost"
  LOCAL: "TRUE"
  TRINO_LOG_LEVEL: "INFO"
  TRINO_S3A_OR_S3: "s3a"
  MINIO_ENDPOINT: "http://koku-minio:9000"
  S3_ACCESS_KEY: "kokuminioaccess"
  S3_SECRET: "kokuminiosecret"
  AWS_ACCESS_KEY_ID: "kokuminioaccess"
  AWS_SECRET_ACCESS_KEY: "kokuminiosecret"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "koku-bucket"
  POSTGRES_SQL_SERVICE_HOST: "db"
  POSTGRES_SQL_SERVICE_PORT: "5432"
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"
