apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash
  namespace: koku
  labels:
    app: unleash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash
  template:
    metadata:
      labels:
        app: unleash
    spec:
      containers:
        - name: unleash
          image: unleashorg/unleash-server:5.8.2
          ports:
            - containerPort: 4242
          envFrom:
            - configMapRef:
                name: koku-config
          volumeMounts:
            - name: shared-storage
              mountPath: /.unleash
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: koku-pvc  

