apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash
  namespace: koku
  labels:
    app: unleash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash
  template:
    metadata:
      labels:
        app: unleash
    spec:
      containers:
        - name: unleash
          image: public.ecr.aws/v0r6c2e2/unleash:latest
          ports:
            - containerPort: 4242
          envFrom:
            - configMapRef:
                name: unleash-config
            - configMapRef:
                name: koku-config
          imagePullPolicy: Always

