apiVersion: v1
kind: Service
metadata:
  name: koku-beat
  namespace: koku
  labels:
    app: koku-beat
spec:
  selector:
    app: koku-beat
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
