apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: koku
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: public.ecr.aws/v0r6c2e2/hive-metastore:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: hive-metastore-config
            - configMapRef:
                name: koku-config
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-storage
              mountPath: /opt/hive-metastore-bin/conf/metastore-site.xml
              subPath: metastore-site.xml
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: hive-metastore-pvc  
