apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: koku
spec:
  type: ClusterIP
  ports:
    - port: 9083
      targetPort: 8000
      name: http
  selector:
    app: hive-metastore
